import { GlassCard } from "../components/ui/GlassCard";

export function Terms({ onNavigate }: { onNavigate: (path: string) => void }) {
  return (
    <div className="relative text-slate-100 min-h-screen overflow-x-hidden">
      <a
        href="#main-content"
        className="sr-only focus:not-sr-only focus:fixed focus:top-4 focus:left-4 focus:z-50 focus:px-4 focus:py-2 focus:rounded-lg focus:bg-obsidian-900 focus:text-white focus:outline focus:outline-2 focus:outline-cyan-400"
      >
        Skip to content
      </a>
      <div className="mesh-glow" />
      <div className="relative max-w-2xl mx-auto px-4 md:px-8 py-16 space-y-8">
        <header>
          <button
            onClick={() => onNavigate("/")}
            className="text-sm text-slate-400 hover:text-white transition-colors"
          >
            ← Runway OS
          </button>
        </header>

        <main id="main-content" className="space-y-8">
        <div className="space-y-2">
          <h1 className="text-3xl font-bold text-white tracking-tight">Terms of Service</h1>
          <p className="text-xs text-[oklch(0.57_0.046_257.417)]">Last updated 21 August 2026.</p>
        </div>

        <GlassCard className="p-5">
          <p className="text-sm text-amber-300/90 leading-relaxed">
            This page accurately documents how Runway OS actually works. It isn't written
            or reviewed by a lawyer — if you need this to be legally binding (e.g. for a
            specific jurisdiction's consumer protection requirements), have a solicitor
            review it before relying on it as-is.
          </p>
        </GlassCard>

        <section className="space-y-2">
          <h2 className="text-lg font-semibold text-white">What Runway OS is</h2>
          <p className="text-sm text-slate-400 leading-relaxed">
            A personal finance calculator that runs in your browser. It helps you track a
            daily safe-to-spend number, flag unused subscriptions, and estimate how long
            your cash reserve lasts. It is not a bank, does not move money, does not link
            to your real bank accounts, and does not provide financial, investment, tax,
            or legal advice — the numbers it shows are only as accurate as what you enter.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-semibold text-white">The trial and subscription</h2>
          <p className="text-sm text-slate-400 leading-relaxed">
            New users get 72 hours of full access from first launch, no card required.
            After that, the Projection Lab and Money Copilot require a paid plan — Monthly
            (£2.99/month) or Annual (£25.00/year) — billed and processed by Stripe.
            Subscriptions renew automatically until cancelled. You can cancel anytime
            through the Billing Portal (Settings → Manage Billing once subscribed); we
            don't offer refunds for partial billing periods unless required by law in
            your jurisdiction.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-semibold text-white">Your data, your responsibility</h2>
          <p className="text-sm text-slate-400 leading-relaxed">
            Your financial data lives in your browser's local storage, not on our
            servers — see the{" "}
            <button
              onClick={() => onNavigate("/privacy")}
              className="text-sky-400 hover:text-sky-300 underline underline-offset-2"
            >
              Privacy Policy
            </button>{" "}
            for the full detail. That means backing it up (Settings → Export Backup) is
            your responsibility — we can't recover data lost from clearing browser
            storage, switching devices, or an uninstall, since we never had a copy of it
            to begin with.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-semibold text-white">AI features</h2>
          <p className="text-sm text-slate-400 leading-relaxed">
            Money Copilot's answers, receipt-scan results, and the morning briefing are
            generated by an AI model and can be wrong — they're a starting point for your
            own judgment, not financial advice, and shouldn't be relied on for decisions
            with real financial consequences without double-checking the numbers
            yourself.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-semibold text-white">No warranty</h2>
          <p className="text-sm text-slate-400 leading-relaxed">
            Runway OS is provided as-is, without warranty of any kind. We do our best to
            keep it accurate and available, but we don't guarantee it will be error-free,
            uninterrupted, or fit for any particular purpose.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-semibold text-white">Changes</h2>
          <p className="text-sm text-slate-400 leading-relaxed">
            We may update these terms as the product changes. Meaningful changes will
            update the date at the top of this page.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-semibold text-white">Contact</h2>
          <p className="text-sm text-slate-400 leading-relaxed">
            Questions about these terms?{" "}
            <a href="mailto:support@runwayos.app" className="text-sky-400 hover:text-sky-300 underline underline-offset-2">
              support@runwayos.app
            </a>
          </p>
        </section>
        </main>
      </div>
    </div>
  );
}
